### ISSUE TITLE
Facing issues while running mininet.py file

### ISSUE THREAD

**Issue by srkmish** [itswindtw/mtd#2]
I installed quagga, mininext and then put the Project folder under pox/pox. However, i am running into issues while executing the below command

sudo python mininet/mtd_mininet.py

The screenshot shows the error encountered. Kindly help. 

![issue](https://cloud.githubusercontent.com/assets/183584/14302942/180ca58e-fb74-11e5-89e1-059926b43a12.PNG)

**Comment by itswindtw** [comment]
It seems that you don't have mininet installed. You can follow the instruction on miniNExT github to install it.

This project was just an experiment and it hasn't had any update for a while. It might not accommodate changes of SDN toolchain in recent years. Good luck.

**Comment by srkmish** [comment]
Hi Meng-Hsin,
I got the project working. I had a different version of mininet installed. Thanks for this wonderful project. I have 2 doubts regarding the below statements. I would be really grateful if you could answer those.

mininext> a1 iperf -s -B 100.0.0.7 -p 8000 &
mininext> b1 iperf -B 110.0.0.11 -p 8000 -i 1 -t 30 -c [current virtual IP of 10.0.0.7]

(1) Is the Host 100.0.0.7 already defined somewhere or does this command set up this host and bind it to a1?
(2) In second command, why are you binding an expired IP (110.0.0.11) to b1? Isn't the "-c" command enough to bind b1 to a client with the current virtual IP?

**Comment by itswindtw** [comment]
1. host 100.0.0.7 is defined in mtd_mininet.py. iperf starts a service to listen incoming connections.
2. b1 is supposed to be an attacker to a1's network, so 110.0.0/24 is not going to be "expired" as it doesn't belongs to a1. I believe I used -B arg to repeat testing attacks by changing ip address.

**Comment by srkmish** [comment]
Ok Cool. Thanks again for responding to my queries. I had one final doubt. Why is quagga necessary for this setup?

**Comment by itswindtw** [comment]
We used quagga bgpd to build our scenario: An edge router can freely assign unused IPs as new virtual IPs for hosts in its administrative domain. I think static route assignment can also do the trick for this demonstration, but we had used quagga for similar projects, so we just copied and modified these setting for this project.
