### ISSUE TITLE
Facing issues while running mininet.py file 

### ISSUE THREAD

**Issue by NabeelShahid7** [itswindtw/mtd#4]
I installed quagga, mininext and then put the Project folder under pox/pox. However, i am running into issues while executing the below command

sudo python mininet/mtd_mininet.py

The screenshot shows the error encountered. 
Not able to resolve the error even though I have mininet 2.1.0.

**Comment by NabeelShahid7** [comment]
![Capture](https://user-images.githubusercontent.com/95036237/144712940-155d1482-4ea4-4d83-81e2-ec0f38bd4d1a.PNG)

**Comment by itswindtw** [comment]
Hi. This project was finished in several years ago. I didn't work on this area since then so unfortunately I can't help your issue. Sorry about that.
